"""
String constants used in metadata transformation
"""

SCHEMA = "$schema"
AT_ID = "@id"
LABEL = "label"
IDENTIFIER = "identifier"
SAMPLE_IDENTIFIER = "sample_identifier"
DESCRIPTION = "description"
HAS_CONTEXT_CATEGORY = "has_context_category"
HAS_CONTEXT_CATEGORY_CONFIDENCE = "has_context_category_confidence"
HAS_MATERIAL_CATEGORY = "has_material_category"
HAS_MATERIAL_CATEGORY_CONFIDENCE = "has_material_category_confidence"
HAS_SPECIMEN_CATEGORY = "has_specimen_category"
HAS_SPECIMEN_CATEGORY_CONFIDENCE = "has_specimen_category_confidence"
INFORMAL_CLASSIFICATION = "informal_classification"
KEYWORDS = "keywords"
KEYWORD = "keyword"
SCHEME_NAME = "scheme_name"
KEYWORD_URI = "keyword_uri"
PRODUCED_BY = "produced_by"
RESPONSIBILITY = "responsibility"
HAS_FEATURE_OF_INTEREST = "has_feature_of_interest"
RESULT_TIME = "result_time"
SAMPLING_SITE = "samplingSite"
LOCATION = "location"
ELEVATION = "elevation"
LATITUDE = "latitude"
LONGITUDE = "longitude"
PLACE_NAME = "place_name"
SUBSAMPLE = "subsample"
REGISTRANT = "registrant"
SAMPLING_PURPOSE = "sampling_purpose"
CURATION = "curation"
ACCESS_CONSTRAINTS = "access_constraints"
CURATION_LOCATION = "curation_location"
RELATED_RESOURCE = "relatedResource"
AUTHORIZED_BY = "authorized_by"
COMPLIES_WITH = "complies_with"
ROLE = "role"
NAME = "name"
