"""
String constants used in metadata transformation
"""

SCHEMA = "$schema"
AT_ID = "@id"
LABEL = "label"
IDENTIFIER = "identifier"
SAMPLE_IDENTIFIER = "sample_identifier"
DESCRIPTION = "description"
HAS_CONTEXT_CATEGORY = "has_context_category"
HAS_CONTEXT_CATEGORY_CONFIDENCE = "has_context_category_confidence"
HAS_MATERIAL_CATEGORY = "has_material_category"
HAS_MATERIAL_CATEGORY_CONFIDENCE = "has_material_category_confidence"
HAS_SPECIMEN_CATEGORY = "has_specimen_category"
HAS_SPECIMEN_CATEGORY_CONFIDENCE = "has_specimen_category_confidence"